name: dlox_generators
description: An interpreters for Dlox languages.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.14.0 <3.0.0'

publish_to: none

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  build_test:
  build_runner:
  test: ^1.0.0
  analyzer:

dependencies:
  build:
  source_gen:
  dlox_annotations:
    path: ../dlox_annotations/